name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.17.4
  google_sign_in: ^6.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: InriaSerif
      fonts:
        - asset: assets/fonts/InriaSerif-Regular.ttf
        - asset: assets/fonts/InriaSerif-Bold.ttf
          weight: 700

  assets:
    - assets/images/logo.png
    - assets/images/komhua.png
    - assets/images/drop.png
    - assets/images/holdon.png
    - assets/images/dont_panic.png
    - assets/images/pidgas.png
    - assets/images/nolift.png
    - assets/images/potectyourhead.png
    - assets/images/run.png
    - assets/images/take_cover.png
    - assets/images/policy.png
    - assets/images/google.png
