name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.2.1     # หรือเวอร์ชันล่าสุด
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  http: ^1.3.0             # ✅ แก้ตรงนี้เป็นเวอร์ชัน 1 ขึ้นไป
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  firebase_core: ^2.25.4           # ✅ ใช้เชื่อม Firebase
  firebase_auth: ^4.17.4           # ✅ ใช้สำหรับ Google Auth
  google_sign_in: ^6.2.1           # ✅ Google Sign-In
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: InriaSerif
      fonts:
        - asset: assets/fonts/InriaSerif-Regular.ttf
        - asset: assets/fonts/InriaSerif-Bold.ttf
          weight: 700

  assets:
    - assets/images/logo.png
    - assets/images/komhua.png
    - assets/images/drop.png
    - assets/images/holdon.png
    - assets/images/dont_panic.png
    - assets/images/pidgas.png
    - assets/images/nolift.png
    - assets/images/potectyourhead.png
    - assets/images/run.png
    - assets/images/take_cover.png
    - assets/images/policy.png
    - assets/images/google.png

